# This Python file uses the following encoding: utf-8
"""autogenerated by genpy from vision/Vision_info.msg. Do not edit."""
import codecs
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct


class Vision_info(genpy.Message):
  _md5sum = "c6ec64f1b224330e0031c42d5bc908c4"
  _type = "vision/Vision_info"
  _has_header = False  # flag to mark the presence of a Header object
  _full_text = """uint32 top 
uint32 left 
uint32 right
uint32 bottom 
bool detected




"""
  __slots__ = ['top','left','right','bottom','detected']
  _slot_types = ['uint32','uint32','uint32','uint32','bool']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       top,left,right,bottom,detected

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(Vision_info, self).__init__(*args, **kwds)
      # message fields cannot be None, assign default values for those that are
      if self.top is None:
        self.top = 0
      if self.left is None:
        self.left = 0
      if self.right is None:
        self.right = 0
      if self.bottom is None:
        self.bottom = 0
      if self.detected is None:
        self.detected = False
    else:
      self.top = 0
      self.left = 0
      self.right = 0
      self.bottom = 0
      self.detected = False

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      _x = self
      buff.write(_get_struct_4IB().pack(_x.top, _x.left, _x.right, _x.bottom, _x.detected))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      end = 0
      _x = self
      start = end
      end += 17
      (_x.top, _x.left, _x.right, _x.bottom, _x.detected,) = _get_struct_4IB().unpack(str[start:end])
      self.detected = bool(self.detected)
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      _x = self
      buff.write(_get_struct_4IB().pack(_x.top, _x.left, _x.right, _x.bottom, _x.detected))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      end = 0
      _x = self
      start = end
      end += 17
      (_x.top, _x.left, _x.right, _x.bottom, _x.detected,) = _get_struct_4IB().unpack(str[start:end])
      self.detected = bool(self.detected)
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill

_struct_I = genpy.struct_I
def _get_struct_I():
    global _struct_I
    return _struct_I
_struct_4IB = None
def _get_struct_4IB():
    global _struct_4IB
    if _struct_4IB is None:
        _struct_4IB = struct.Struct("<4IB")
    return _struct_4IB
